version: "3.8"

services:
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: notebook
    volumes:
      - db:/var/lib/postgresql/data

  # web:
  #   env_file: .env
  #   container_name: web
  #   build:
  #     context: .
  #     dockerfile: ./apps/web/Dockerfile
  #   restart: always
  #   expose:
  #     - 3000
  #   ports:
  #     - 3000:3000

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
volumes:
  mongodb_data_container:
  db:
    driver: local
